# Generated by Django 5.1.7 on 2025-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, choices=[('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue')], default='blue', max_length=100, null=True)),
                ('amount', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
