# Generated by Django 5.1.7 on 2025-03-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, choices=[('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue')], default='blue', max_length=100, null=True)),
                ('amount', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_of_the_user', to='user.user')),
            ],
        ),
    ]
