# Generated by Django 5.1.7 on 2025-03-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='number',
        ),
    ]
