# Generated by Django 5.1.7 on 2025-03-28 13:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region='IR'),
            preserve_default=False,
        ),
    ]
